'use strict';
window.BSS.AudioManager=class {
 constructor(){this.enabled=false;this.ctx=null;this.musicTime=0;this.note=0;this.volume=.2;}
 start(){try{this.ctx ||= new (window.AudioContext||window.webkitAudioContext)();this.ctx.resume();}catch{} }
 tone(freq,duration,type='square',volume=.13,delay=0){if(!this.enabled||!this.ctx)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume*this.volume,t+.005);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.ctx.destination);o.start(t);o.stop(t+duration+.01);}
 noise(duration,vol){if(!this.enabled||!this.ctx)return;const buffer=this.ctx.createBuffer(1,this.ctx.sampleRate*duration,this.ctx.sampleRate),a=buffer.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*Math.pow(1-i/a.length,.7);const s=this.ctx.createBufferSource(),g=this.ctx.createGain(),filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=1700;s.buffer=buffer;g.gain.value=vol*this.volume;s.connect(filter);filter.connect(g);g.connect(this.ctx.destination);s.start();}
 play(name){if(name==='whistle'){this.tone(2200,.22,'sine',.28);this.tone(2550,.22,'sine',.12,.06);}else if(name==='goal'){this.noise(2,.8);[523,659,784,1046].forEach((f,i)=>this.tone(f,.3,'square',.17,i*.12));}else if(name==='post'){this.tone(330,.35,'triangle',.6);}else if(name==='save'){this.noise(.16,.3);}else if(name==='kick'){this.tone(95,.09,'triangle',.8);this.noise(.05,.3);}else if(name==='menu'){this.tone(660,.06,'square',.2);}else this.tone(150,.05,'triangle',.35);}
 update(dt,menu){if(!this.enabled)return;this.musicTime-=dt;if(this.musicTime<=0){this.musicTime=menu?.22:2.8;if(menu){const melody=[64,67,71,67,62,66,69,74,64,71,69,67,62,66,64,59];const n=melody[this.note++%melody.length];this.tone(440*Math.pow(2,(n-69)/12),.16,'square',.065);if(this.note%2===0)this.tone(110*Math.pow(2,([0,0,5,7][Math.floor(this.note/4)%4])/12),.19,'triangle',.12);}else this.noise(.8,.08);}}
};
