'use strict';
// Presentation owns its timeline. Replays render snapshots and never step physics.
(() => {
 const B=window.BSS;
 B.Cinematics=class {
  constructor(match){this.m=match;this.queue=[];this.frames=[];this.sample=0;this.goals=new Map();this.trailing=[false,false];this.rng=B.rng((match.options.seed??Date.now())+971);this.enabled=match.options.cutscenes!==false&&!match.autoplay&&match.mode!=='training';if(this.enabled&&match.mode!=='penalties')this.add('toss',18,{stage:0,choice:0});}
  get active(){return this.queue[0];}
  add(type,duration,data={},done){if(this.enabled)this.queue.push({type,duration,data,done,time:0});}
  capture(){const m=this.m,teams=m.teams.map(t=>({...t,stats:{...t.stats},players:[]})),map=new Map();m.players.forEach(p=>{const q={...p,facing:{...p.facing},team:teams[p.team.side]};map.set(p,q);q.team.players.push(q);});const ball={...m.ball,net:m.ball.net?{...m.ball.net}:null,trail:m.ball.trail.map(p=>({...p})),owner:map.get(m.ball.owner),lastTouch:map.get(m.ball.lastTouch)};const f={...m,cinema:null,teams,players:teams.flatMap(t=>t.players),minute:m.minute,ball,controlled:map.get(m.controlled),lastScorer:map.get(m.lastScorer),freeKick:null,bannerTime:0,charges:{},restart:m.restart?{...m.restart,taker:map.get(m.restart.taker)}:null};if(m.penalty)f.penalty={...m.penalty,taker:map.get(m.penalty.taker),keeper:map.get(m.penalty.keeper),dive:m.penalty.dive?{...m.penalty.dive}:null};if(m.penalties)f.penalties={...m.penalties,scores:[...m.penalties.scores],kicks:m.penalties.kicks.map(k=>[...k])};this.frames.push(f);if(this.frames.length>140)this.frames.shift();}
  record(dt){if(!this.enabled)return;this.sample+=dt;if(this.sample>=.05){this.sample%=.05;this.capture();}for(let i=0;i<2;i++)if(this.m.teams[i].score<this.m.teams[1-i].score)this.trailing[i]=true;}
  replay(label){if(this.frames.length<2)return;const frames=this.frames.slice();this.add('replay',Math.min(9,frames.length*.05/.75),{frames,label});}
  goal(data){const m=this.m,side=data.team,p=m.lastScorer,own=data.ownGoal||p?.team.side!==side;const key=side+':'+p?.id,count=own?0:(this.goals.get(key)||0)+1;if(!own)this.goals.set(key,count);this.capture();this.replay('REPLAY DO GOL');this.add('goal',3.6,{side,player:p,own});if(this.trailing[side]&&m.teams[side].score>m.teams[1-side].score){this.trailing[side]=false;this.add('comeback',3.4,{side,player:p});}if(count===3)this.add('hat',4,{side,player:p});for(let i=0;i<2;i++)if(m.teams[i].score<m.teams[1-i].score)this.trailing[i]=true;this.frames=[];}
  referee(penalty){this.add('referee',2.7,{penalty,card:this.card});this.card=null;if(penalty)this.replay('REPLAY DA INFRAÇÃO');this.frames=[];}
  substitution(old,fresh){this.add('sub',3.8,{side:fresh.team.side,old,player:fresh});this.frames=[];}
  next(){const s=this.queue.shift();this.m.charges={};this.m.bufferedShot=null;s?.done?.();}
  update(dt,input){const s=this.active;if(!s)return;const a=input?.pressed||{};s.time+=dt;
   if(s.type==='toss'){const d=s.data;if(d.stage===0){if(a.left||a.right)d.choice=1-d.choice;if(a.pass||a.shoot||a.long||s.time>8){d.result=this.rng()<.5?0:1;d.winner=d.result===d.choice?this.m.human:1-this.m.human;d.stage=1;s.time=0;}}else if(d.stage===1&&s.time>2.5){d.stage=2;s.time=0;d.choice=0;}else if(d.stage===2){if(a.left||a.right)d.choice=1-d.choice;if((d.winner===this.m.human&&(a.pass||a.shoot||a.long))||s.time>(d.winner===this.m.human?8:2)){const side=d.choice===0?d.winner:1-d.winner;this.m.openingSide=side;if(d.choice===1)this.m.teams.forEach(t=>t.dir*=-1);this.m.kickoff(side);this.next();}}return;}
   if(s.time>=s.duration||s.time>.4&&(a.pass||a.shoot||a.long))this.next();
  }
 };
 const M=B.Match.prototype,update=M.update,event=M.event,restart=M.setRestart,penalty=M.setupPenalty,finish=M.finish,resolve=M.resolvePenalty,resumeHalf=M.resumeHalf;
 M.update=function(dt,input){if(this.cinema?.active){this.cinema.update(dt,input);return;}this.cinema?.record(dt);update.call(this,dt,input);};
 M.event=function(type,data={}){if(this.cinema?.enabled){if(type==='foul')this.cinema.card=data.red?'red':data.yellow?'yellow':null;if(type==='goal'){if(this.state==='penalty')this.cinema.penaltyGoal=data;else{this.cinema.goal(data);const last=this.cinema.queue.at(-1);if(last)last.done=()=>this.kickoff(this.nextKickoff);}}}return event.call(this,type,data);};
 M.setRestart=function(type,...args){restart.call(this,type,...args);if(type==='FALTA')this.cinema?.referee(false);};
 M.setupPenalty=function(side,shootout){if(!shootout)this.cinema?.referee(true);return penalty.call(this,side,shootout);};
 M.resolvePenalty=function(){if(this.cinema?.enabled&&this.cinema.penaltyGoal){const data=this.cinema.penaltyGoal;this.cinema.penaltyGoal=null;this.cinema.goal(data);this.cinema.queue.at(-1).done=()=>resolve.call(this);return;}return resolve.call(this);};
 M.finish=function(){if(this.finished||this.cinema?.ending)return;if(this.cinema?.enabled){this.cinema.ending=true;const [a,b]=this.teams;const side=this.penalties?.winner??(a.score===b.score?null:a.score>b.score?0:1);this.sound.play('whistle');this.cinema.add('final',5.5,{side},()=>finish.call(this));}else finish.call(this);};
 M.resumeHalf=function(){resumeHalf.call(this);if(this.openingSide!==undefined)this.kickoff(this.period%2?this.openingSide:1-this.openingSide);};
 const R=B.Renderer.prototype,render=R.render;
 R.render=function(m,dt,...args){const s=m.cinema?.active;document.body.classList.toggle('cinematic-active',!!s);if(!s){render.call(this,m,dt,...args);return;}this.fit(false);const g=this.ctx;g.save();g.setTransform(1,0,0,1,48,15);g.imageSmoothingEnabled=false;
  if(s.type==='replay'){const frames=s.data.frames,f=frames[Math.min(frames.length-1,Math.floor(s.time*.75/.05))];render.call(this,f,dt,false,60,false);this.rect(-48,-15,480,25,'#071923');this.text(s.data.label+'  •  0.75x',192,2,'#ffe380',9,'center');this.rect(-48,209,480,46,'#071923');this.rect(-32,237,448,2,'#395755');this.rect(-32,237,448*Math.min(1,s.time/s.duration),2,'#ffe380');this.text('PASSE / CHUTE: PULAR',192,250,'#d7e7df',7,'center');}
  else this.cutscene(m,s);g.restore();
 };
 R.cutscene=function(m,s){const t=s.time,d=s.data,g=this.ctx;
  this.rect(-48,-15,480,270,'#0a1829');this.rect(-48,39,480,88,'#20394c');for(let row=0;row<6;row++)for(let x=-40;x<432;x+=9){const y=47+row*12+(Math.sin(t*5+x+row)>0?1:0);this.rect(x,y,4,5,['#d5b47b','#739e9a','#cb6f60','#e5d9b3'][(x+40+row)%4]);}this.rect(-48,116,480,12,'#dae3c3');this.text('B R A S I L   S U P E R   S O C C E R',192,125,'#243d42',7,'center');for(let i=0;i<6;i++)this.rect(-48,128+i*17,480,17,i%2?'#328252':'#2b764c');this.rect(-48,206,480,2,'#c5d4a4');
  const actor=(p,x,y,pose='idle',scale=3)=>{if(!p)return;this.rect(x-19,y-3,38,5,'#163e38');const jump=pose==='celebrate'?Math.max(0,Math.sin(t*8))*9:0;g.drawImage(this.sprite({...p,anim:pose,animTime:0,runTime:t*9,facing:{x:0,y:1}}),Math.round(x-14*scale),Math.round(y-28*scale-jump),28*scale,30*scale);};
  const ref=(gesture)=>{const skin='#dfab7b',shirt='#e5c951';this.rect(180,110,24,22,skin);this.rect(180,105,24,7,'#20272d');this.rect(183,117,3,3,'#20272d');this.rect(197,117,3,3,'#20272d');this.rect(189,128,7,2,'#9b5f45');this.rect(187,132,10,5,skin);this.rect(176,135,32,38,shirt);this.rect(176,173,32,13,'#142736');this.rect(177,186,10,26,'#e5c951');this.rect(198,186,10,26,'#e5c951');this.rect(173,208,15,6,'#142736');this.rect(198,208,15,6,'#142736');if(gesture==='point'){this.rect(205,137,38,9,shirt);this.rect(242,137,17,8,skin);}else{this.rect(168,126,10,27,shirt);this.rect(166,115,10,17,skin);}this.rect(208,143,10,23,shirt);if(d.card){this.rect(165,97,12,18,d.card==='red'?'#ff5449':'#ffe16b');}else if(gesture==='whistle'){this.rect(165,121,21,7,skin);this.rect(184,121,9,5,'#e5e8df');for(let i=0;i<3;i++)this.rect(209+i*7,116+i*5,4,2,'#f7e7b1');}};
  let title='',sub='',hint='PASSE / CHUTE: PULAR';const side=d.side??0,team=m.teams[side];
  if(s.type==='toss'){title='CARA OU COROA';actor(m.teams[0].players[1],105,211);actor(m.teams[1].players[1],283,211);ref('toss');if(d.stage===0){sub='ESCOLHA: '+(d.choice===0?'[ CARA ]   COROA':'CARA   [ COROA ]');hint='DIREÇÃO: ESCOLHER  •  PASSE / CHUTE: CONFIRMAR';}else if(d.stage===1){const y=99-Math.sin(Math.min(1,t/2.5)*Math.PI)*52,w=Math.max(2,Math.abs(Math.cos(t*16))*17);this.rect(192-w/2,y,w,18,'#f3cb55');this.rect(192-w/2+2,y+3,Math.max(1,w-4),12,'#fff0a6');sub=t<1.8?'A MOEDA ESTÁ NO AR...':(d.result===0?'CARA':'COROA')+'!';hint='SORTEIO DOS CAPITÃES';}else{title=m.teams[d.winner].data.shortName+' VENCEU O SORTEIO';sub=d.choice===0?'[ SAÍDA DE BOLA ]  TROCAR LADO':'SAÍDA DE BOLA  [ TROCAR LADO ]';hint=d.winner===m.human?'DIREÇÃO + PASSE / CHUTE: CONFIRMAR':'O ADVERSÁRIO ESTÁ ESCOLHENDO...';}}
  if(s.type==='referee'){title=d.penalty?'PÊNALTI!':'FALTA!';sub=d.card==='red'?'CARTÃO VERMELHO':d.card==='yellow'?'CARTÃO AMARELO':d.penalty?'O ÁRBITRO APONTA PARA A MARCA':'APITO DO ÁRBITRO';ref(t<1?'whistle':'point');actor(m.teams[0].players[2],95,217);actor(m.teams[1].players[2],285,217);}
  if(['goal','comeback','hat'].includes(s.type)){title=s.type==='hat'?'HAT-TRICK!':s.type==='comeback'?'É A VIRADA!':d.own?'GOL CONTRA!':'GOOOOOL!';sub=s.type==='hat'?'TRÊS GOLS DE '+d.player.name:d.own?team.data.name:(d.player?.name||team.data.name);actor(team.players[4],125-Math.max(0,1-t)*80,218,'celebrate',2.7);actor(team.players[7],260+Math.max(0,1-t)*80,218,'celebrate',2.7);actor(d.own?team.players[9]:d.player,192,216,'celebrate',3.6);if(s.type==='hat')for(let i=0;i<3;i++)g.drawImage(this.ballFrame(t+i),160+i*25,193,17,17);if(s.type==='comeback'){this.rect(111,70,162,25,'#10263a');this.text(m.teams.map(t=>t.score).join('  :  '),192,89,'#ffe480',20,'center');}}
  if(s.type==='sub'){title='SUBSTITUIÇÃO';sub='SAI '+d.old.name+'  •  ENTRA '+d.player.name;const walk=Math.min(1,t/2.6);actor(d.old,145-walk*150,218,'run');actor(d.player,340-walk*95,218,'run');ref('toss');this.rect(151,75,83,29,'#071a25');this.text(String(d.old.shirtNumber??d.old.index+1),169,96,'#ff8277',16,'center');this.text(String(d.player.shirtNumber??d.player.index+1),213,96,'#97edaa',16,'center');}
  if(s.type==='final'){title='FIM DE JOGO';sub=d.side===null?'EMPATE • GRANDE PARTIDA!':team.data.name+' VENCEU!';for(let i=0;i<7;i++)actor((d.side===null?m.teams[i%2]:team).players[i+1],28+i*55,209+(i%2)*8,d.side===null?'idle':'celebrate',2.4);if(d.side!==null)for(let i=0;i<50;i++)this.rect(-40+(i*47)%470,42+(i*19+t*(22+i%7))%163,3,5,['#f2da77','#df6c71','#91c7dd'][i%3]);this.rect(132,68,120,25,'#10263a');this.text(m.teams.map(t=>t.score).join(' : '),192,87,'#ffe480',19,'center');}
  this.rect(-48,-15,480,48,'#091a2c');this.rect(-48,30,480,3,'#ddbb66');this.text(title,192,16,'#ffe6a0',19,'center');this.rect(-48,221,480,34,'#091a2c');this.text(sub.toUpperCase().slice(0,66),192,234,'#fff0c9',sub.length>48?6:8,'center');this.text(hint,192,248,'#95b8bd',6,'center');
  const fade=Math.max(0,1-t/.2);if(fade){g.fillStyle=`rgba(3,10,18,${fade})`;g.fillRect(-48,-15,480,270);}
 };
})();
