'use strict';
(() => {
 const B=window.BSS,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const button=(id,label,primary=false)=>`<button id="${id}" class="${primary?'primary':''}">${label}</button>`;
 const regularSelection=B.UI.prototype.selection;
 B.UI.prototype.selection=function(){if(['league','cup','penalty-cup'].includes(this.setup.mode)&&!this.setup.competition)return this.competitionSelection();return regularSelection.call(this);};
 B.UI.prototype.competitionSelection=function(){
  const a=this.app,s=this.setup,defs=a.competition.definitions(s.mode==='league'?'league':'cup');let def=defs.find(d=>d.id===s.competitionId)||defs[0];s.competitionId=def.id;
  const ids=[...def.teams,...def.lateEntrants||[]],clubs=ids.map(id=>a.data.get(id));if(!ids.includes(s.home))s.home=ids[0];const selected=a.data.get(s.home);
  this.show(`${this.head(s.mode==='penalty-cup'?'COPA DE PÊNALTIS':'TEMPORADA 2026',s.mode==='league'?'Escolha sua divisão':'Escolha sua copa')}<div class="competition-picker"><label for="competition-id">${s.mode==='league'?'DIVISÃO':'COMPETIÇÃO'}</label><select id="competition-id">${defs.map(d=>`<option value="${d.id}" ${d.id===def.id?'selected':''}>${esc(d.name)}</option>`).join('')}</select></div><div class="panels competition-panels"><div class="panel"><label for="home-team">SEU CLUBE · ${def.teams.length} EQUIPES${def.lateEntrants?' + 20 NA QUINTA FASE':''}</label><input id="club-search" type="search" placeholder="Buscar clube…" aria-label="Buscar clube"><select id="home-team">${clubs.map(t=>`<option value="${t.id}" ${t.id===s.home?'selected':''}>${esc(t.name)}${def.lateEntrants?.includes(t.id)?' · entra na 5ª fase':''}</option>`).join('')}</select><div id="home-card">${this.clubCard(s.home)}</div><p class="micro">Elenco: ${selected.rosterStatus==='season-roster'?'lista da temporada; vínculos atuais não integralmente confirmados':'lista publicada pela fonte em 09/10/2026'}.</p><details><summary>Elenco e referência de cores</summary><p class="micro"><a href="${esc(selected.source)}" target="_blank" rel="noopener">Fonte do elenco</a> · <a href="${esc(selected.kitSource)}" target="_blank" rel="noopener">Cores do clube</a><br>${esc(selected.kitNote)}</p><div class="roster">${selected.players.map(p=>`<div class="roster-row"><small>${p.shirtNumber??'—'}</small><span>${esc(p.name)}</span><b>${p.position}</b></div>`).join('')}</div></details></div><div class="panel"><h3>Como funciona</h3><p class="sub">${esc(def.description)}</p>${s.mode==='penalty-cup'?`<p class="notice">${esc(a.data.raw.competitions.penaltyRules)}</p>`:''}<p class="notice">Temporada simulada: resultados começam do zero. Grupos e participantes de 2026; calendário e sorteios seguintes gerados pelo jogo. Progresso salvo após cada confronto.</p>${def.groups?`<details><summary>Ver todos os grupos</summary>${def.groups.map((g,i)=>`<p class="sub"><b>Grupo ${def.format==='d'?i+1:String.fromCharCode(65+i)}</b><br>${g.map(id=>esc(a.data.get(id).name)).join(' · ')}</p>`).join('')}</details>`:''}</div></div><div class="settings-grid"><div><label for="difficulty">DIFICULDADE</label><select id="difficulty">${['Fácil','Normal','Difícil','Craque'].map((x,i)=>`<option value="${i}" ${i===a.settings.difficulty?'selected':''}>${x}</option>`).join('')}</select></div><div><label for="duration">DURAÇÃO DA PARTIDA</label><select id="duration">${[120,240,360,600].map(v=>`<option value="${v}" ${v===a.settings.duration?'selected':''}>${v/60} minutos</option>`).join('')}</select></div></div><div class="button-row">${button('next','INICIAR COMPETIÇÃO →',true)}</div>`);
  this.click('back',()=>this.home());document.getElementById('competition-id').onchange=e=>{s.competitionId=e.target.value;this.competitionSelection();};document.getElementById('home-team').onchange=e=>{s.home=e.target.value;this.competitionSelection();};document.getElementById('club-search').oninput=e=>{const q=e.target.value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();for(const o of document.getElementById('home-team').options)o.hidden=!o.text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(q);};
  this.click('next',()=>{a.settings.difficulty=+document.getElementById('difficulty').value;a.settings.duration=+document.getElementById('duration').value;a.saveSettings();a.competition.create(s.mode,s.home,a.data.teams,s.competitionId);this.competition();});
 };
 B.UI.prototype.competition=function(){
  const a=this.app,m=a.competition,c=m.current;if(!c)return this.home();document.body.classList.remove('playing');a.match=null;
  const name=id=>esc(a.data.get(id)?.name||id),fixture=m.fixture();
  const table=rows=>`<div class="table-scroll"><table><thead><tr><th>#</th><th>CLUBE</th>${['P','J','V','E','D','GP','GC','SG','CV','CA'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map((t,i)=>`<tr class="${t.id===c.team?'mine':''}"><td>${i+1}</td><td>${name(t.id)}</td>${[t.p,t.j,t.v,t.e,t.d,t.gp,t.gc,t.gp-t.gc,t.red,t.yellow].map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const games=rounds=>rounds.map((r,i)=>`<div class="bracket">${r.map(g=>`<div class="fixture ${[g.home,g.away].includes(c.team)?'mine':''}"><label>${g.leg?(g.leg===1&&rounds.length===2?'IDA':g.leg===2?'VOLTA':'JOGO ÚNICO'):'RODADA '+(i+1)}</label>${name(g.home)} <b>${g.result?g.result.join(' × '):'×'}</b> ${name(g.away)}${g.penalties&&!c.penaltyOnly?`<div class="micro">Pênaltis ${g.penalties.join(' × ')}</div>`:''}${g.decidingPenalties?`<div class="micro">Desempate ${g.decidingPenalties.join(' × ')}</div>`:''}${g.winner?`<div class="micro">CLASSIFICADO: ${name(g.winner)}</div>`:''}</div>`).join('')}</div>`).join('');
  const qualifications=Object.entries(c.qualified||{}).map(([k,ids])=>`<p class="sub"><b>${({libertadoresGroups:'Libertadores · grupos',libertadoresPreliminary:'Libertadores · preliminar',sudamericana:'Sul-Americana',serieD2027:'Vaga assegurada na Série D 2027 (exceto promovidos)'})[k]||k}:</b> ${ids.filter(id=>!c.promoted.includes(id)).map(name).join(', ')}</p>`).join('');
  this.show(`${this.head(c.penaltyOnly?'COPA DE PÊNALTIS':'SUA TEMPORADA',esc(c.name),'Menu')}<div class="notice">${c.complete?`CAMPEÃO: ${name(c.champion)}`:`${esc(c.stageName)} · ${c.phase==='groups'?'Rodada '+(c.round+1)+' de '+c.rounds.length:c.rounds.length===2?(c.round===0?'Ida':'Volta'):'Jogo único'}`} · ${name(c.team)}</div>${c.promoted.length?`<p class="notice">ACESSO: ${c.promoted.map(name).join(' · ')}</p>`:''}${c.relegated.length?`<p class="notice">REBAIXADOS: ${c.relegated.map(name).join(' · ')}</p>`:''}${qualifications}${c.qualificationPending?'<p class="micro">Vagas continentais provisórias até informar os campeões das copas abaixo.</p>':''}${c.transferred?.length?`<details><summary>Terceiros da Libertadores → Sul-Americana</summary><p>${c.transferred.map(name).join(' · ')}</p></details>`:''}
  ${c.phase==='groups'?c.groups.map((g,i)=>`<h3>${c.groups.length>1?'Grupo '+(c.format==='d'?i+1:String.fromCharCode(65+i)):'Classificação'}</h3>${table(m.standings(i))}`).join(''):games(c.rounds)}
  ${fixture?`<div class="club-card"><div><label>${fixture.needsTiebreak?'AGREGADO EMPATADO · DISPUTA EXTRA':'SEU PRÓXIMO JOGO'}</label><h3>${name(fixture.home)} × ${name(fixture.away)}</h3>${fixture.leg===2?`<p>Ida: ${c.rounds[0].find(g=>g.tie===fixture.tie).result.join(' × ')}</p>`:''}</div></div>`:!c.complete?'<p class="sub">Seu clube não joga nesta rodada. Avance para acompanhar a competição.</p>':''}
  <div class="button-row">${button('new-season','NOVA COMPETIÇÃO')}${!c.complete?button('play-fixture',fixture?'PREPARAR PRÓXIMO JOGO →':'AVANÇAR RODADA →',true):''}</div>
  ${c.stages.length?`<details><summary>Histórico das fases</summary>${c.stages.map(st=>`<details><summary>${esc(st.name)}</summary>${st.groups.length?st.groups.map(g=>table(m.rank(st.table.filter(t=>g.includes(t.id)),st.rounds.flat(),['libertadores','sul-americana'].includes(c.id),!(c.format==='c'&&st.id==='groups')))).join(''):''}${games(st.rounds)}</details>`).join('')}</details>`:''}
  ${c.shadowGroups?`<details><summary>Grupos simulados da ${c.shadowGroups.competition}</summary>${c.shadowGroups.ranks.map(table).join('')}${games(c.shadowGroups.rounds)}</details>`:''}${c.complete&&c.format==='a'?this.qualificationForm():''}`);
  this.click('back',()=>this.home());this.click('new-season',()=>{this.setup.mode=c.penaltyOnly?'penalty-cup':c.type;this.setup.competition=false;this.setup.competitionId=c.id;this.selection();});this.click('play-fixture',()=>{if(!fixture){m.completeRound();this.competition();return;}const human=fixture.home===c.team?0:1;this.setup={...this.setup,home:fixture.home,away:fixture.away,...m.matchOptions(fixture),competitionId:c.id,human,formation:a.data.get(c.team).formation,lineup:[...a.data.get(c.team).players],penaltyOrder:null,penaltyKeeper:null};this.lineupCompetition(human);});
  this.click('apply-qualification',()=>{const values=Object.fromEntries(['cupChampion','cupRunnerUp','libChampion','sudChampion'].map(k=>[k,document.getElementById(k).value||null]));values.promotedB=[0,1,2,3].map(i=>document.getElementById("promoted-b-"+i).value);try{m.updateQualification(values);this.competition();}catch(e){this.toast(e.message);}});
 };
 B.UI.prototype.qualificationForm=function(){const c=this.app.competition.current;const promoted=this.app.competition.definition('serie-b').teams;const promotedForm=[0,1,2,3].map(i=>`<div><label for="promoted-b-${i}">Acesso da Série B · ${i+1}</label><select id="promoted-b-${i}"><option value="">Não informado</option>${promoted.map(id=>`<option value="${id}" ${c.cupResults?.promotedB?.[i]===id?'selected':''}>${esc(this.app.data.get(id).name)}</option>`).join('')}</select></div>`).join('');return `<details><summary>Definir resultados das copas e recalcular vagas</summary><p class="micro">Escolha os resultados da sua temporada simulada e os quatro promovidos da Série B. Clubes fora da Série A de 2027 não recebem vaga na Libertadores. Sem informar, o jogo mostra apenas as vagas básicas do Brasileirão.</p><div class="settings-grid">${[['cupChampion','Campeão da Copa do Brasil'],['cupRunnerUp','Vice da Copa do Brasil'],['libChampion','Campeão da Libertadores'],['sudChampion','Campeão da Sul-Americana']].map(([key,label])=>`<div><label for="${key}">${label}</label><select id="${key}"><option value="">Não informado</option>${this.app.data.teams.map(t=>`<option value="${t.id}" ${c.cupResults?.[key]===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></div>`).join('')}${promotedForm}</div>${button('apply-qualification','RECALCULAR VAGAS')}</details>`;};
})();
