'use strict';
window.BSS.Game=class {
 constructor(data){const B=window.BSS;this.data=data;this.input=new B.InputManager();this.touch=new B.TouchControls(this.input);this.display=new B.DisplaySettings();this.audio=new B.AudioManager();this.renderer=new B.Renderer(document.getElementById('game'));this.competition=new B.CompetitionManager();this.settings={difficulty:1,duration:240,stadium:'day',...B.safeStorage.get('settings',{})};this.match=null;this.preview=new B.Match(data.teams[0],data.teams[1],{autoplay:true,mode:'training',seed:26});this.ui=new B.UI(this);this.paused=false;this.debug=false;this.engine=new B.GameEngine(dt=>this.update(dt),alpha=>this.render(alpha));this.input.onBlur=()=>{if(this.match&&!this.paused&&!this.match.finished)this.pause();};this.engine.start();this.ui.home();}
 start(home,away,options){const B=window.BSS;this.match=new B.Match(this.data.get(home),this.data.get(away),{...this.settings,...options},this.audio);this.match.cinema=new B.Cinematics(this.match);this.match.onEvent=(type)=>{if(type==='half'){this.paused=true;this.ui.pause(true);}if(type==='finished'){this.paused=true;const m=this.match;if(options.competition)this.competition.record(home,away,m.teams.map(t=>t.score),m.penalties);const history=B.safeStorage.get('history',[]);history.unshift({home,away,score:m.teams.map(t=>t.score),stats:m.teams.map(t=>t.stats),date:new Date().toISOString()});B.safeStorage.set('history',history.slice(0,30));this.ui.result();}};this.paused=false;this.audio.start();this.ui.clear();this.touch.reset();this.input.clear();this.input.enabled=true;document.body.classList.remove('touch-defending');document.body.classList.add('playing');document.getElementById('game').focus();}
 pause(){if(!this.match||this.match.finished)return;this.paused=true;this.touch.reset();this.input.enabled=false;this.ui.pause(this.match.state==='half');}
 resume(){if(this.match?.state==='half')this.match.resumeHalf();this.paused=false;this.input.clear();this.match.charges={};this.input.enabled=true;this.ui.clear();document.getElementById('game').focus();}
 update(dt){this.input.poll(dt);if(this.input.pressed.pause&&this.match&&!this.match.finished){if(this.paused)this.resume();else this.pause();}if(this.match){if(!this.paused)this.match.update(dt,this.input);
      const owner=this.match.ball.owner;
      if(owner)document.body.classList.toggle('touch-defending',owner.team.side!==this.match.human);
      if(this.match.state==='penalty')document.body.classList.toggle('touch-defending',this.match.penalty.side!==this.match.human);
     }else{this.preview.update(dt);if(this.preview.state==='half')this.preview.resumeHalf();}this.audio.update(dt,!this.match);}
 render(){this.renderer.render(this.match||this.preview,1/60,this.debug,this.engine.fps,!this.match);}
 saveSettings(){return window.BSS.safeStorage.set('settings',this.settings);}
};
