'use strict';
(() => {
 const B=window.BSS;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const button=(id,text,primary=false)=>`<button id="${id}" class="${primary?'primary':''}">${text}</button>`;
 B.UI=class {
  constructor(app){this.app=app;this.el=document.getElementById('screen');this.setup={home:'flamengo',away:'palmeiras',mode:'quick',formation:'4-4-2',tactics:{...B.DEFAULT_TACTICS}};this.selectedSlot=null;}
  show(html){this.el.innerHTML=this.app.display.toolbar()+html;this.app.display.bind(this.el);document.body.classList.add('ui-open');this.app.touch?.reset();this.app.input.enabled=false;this.el.scrollTop=0;}
  clear(){this.el.innerHTML='';document.body.classList.remove('ui-open');}
  click(id,fn){const e=document.getElementById(id);if(e)e.onclick=()=>{this.app.audio.start();this.app.audio.play('menu');fn();};}
  toast(text){const e=document.getElementById('toast');e.textContent=text;e.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>e.classList.remove('show'),3500);}
  head(kicker,title,back='Voltar'){return `<div class="screen-head"><div><div class="eyebrow">${kicker}</div><h2>${title}</h2></div>${button('back','← '+back)}</div>`;}
  home(){this.app.match=null;this.app.paused=false;document.body.classList.remove('playing');this.show(`<div class="home-layout"><div class="home-intro"><div class="eyebrow">O FUTEBOL BRASILEIRO. EM 16 BITS.</div><h1>BRASIL<br><em>SUPER</em><br>SOCCER<small>20 — 26</small></h1><p class="tagline">O campo é seu. A história também.<br>Vinte clubes. Uma paixão. Aperte o play.</p></div><nav class="mode-list" aria-label="Modos de jogo">${[['quick','PARTIDA RÁPIDA'],['league','BRASILEIRÃO'],['cup','COPA'],['penalties','PÊNALTIS'],['training','TREINO'],['options','OPÇÕES & CONTROLES']].map(([id,name],i)=>`<button id="mode-${id}" class="${i===0?'primary':''}"><span>0${i+1}</span><strong>${name}</strong><i>↗</i></button>`).join('')}</nav></div><div class="hero-note"><b>FUTEBOL DE VERDADE. ALMA DE ARCADE.</b>ARTE ORIGINAL · JOGUE OFFLINE<br>TECLADO + GAMEPAD + TOQUE</div><div class="micro">BUILD 1.0 · DADOS CONSULTADOS EM 30 SET 2026</div>`);
   for(const mode of ['quick','league','cup','penalties','training'])this.click('mode-'+mode,()=>{if(['league','cup'].includes(mode)&&this.app.competition.current?.type===mode)this.competition();else{this.setup.mode=mode;this.setup.competition=false;this.setup.human=0;this.selection();}});this.click('mode-options',()=>this.options());}
  clubOptions(id){return this.app.data.teams.map(t=>`<option value="${t.id}" ${t.id===id?'selected':''}>${esc(t.name)}</option>`).join('');}
  clubCard(id){const t=this.app.data.get(id);return `<div class="club-card"><div class="club-badge" style="background:${t.primaryColor};color:${t.secondaryColor}">${t.shortName}</div><div><h3>${esc(t.name)}</h3><p>${esc(t.city)} · ${esc(t.stadium)}</p><p style="margin-top:8px">${t.players.length} atletas · ${t.formation}</p></div></div>`;}
  selection(){document.body.classList.remove('playing');const s=this.setup;const names={quick:'Partida rápida',league:'Novo Brasileirão',cup:'Nova Copa',penalties:'Disputa de pênaltis',training:'Campo de treino'};this.show(`${this.head('ESCOLHA SEU LADO',names[s.mode])}<div class="panels"><div class="panel"><label for="home-team">${['league','cup'].includes(s.mode)?'SEU CLUBE':'TIME DA CASA · VOCÊ'}</label><select id="home-team">${this.clubOptions(s.home)}</select><div id="home-card">${this.clubCard(s.home)}</div><p class="sub">Vista as cores. Entre para decidir.</p></div><div class="versus">VS</div><div class="panel"><label for="away-team">${['league','cup'].includes(s.mode)?'COMPETIÇÃO':'TIME VISITANTE · CPU'}</label>${['league','cup'].includes(s.mode)?`<h2>${s.mode==='league'?'38 RODADAS':'MATA-MATA'}</h2><p class="sub">${s.mode==='league'?'20 clubes. Turno e returno. Cada ponto conta.':'8 clubes. Quartas, semifinal e final. Prorrogação e pênaltis.'}</p><p class="notice">Calendário gerado pelo jogo. Progresso salvo ao final de cada partida.</p>`:`<select id="away-team">${this.clubOptions(s.away)}</select><div id="away-card">${this.clubCard(s.away)}</div>`}</div></div><div class="settings-grid"><div><label for="difficulty">DIFICULDADE</label><select id="difficulty">${['Fácil','Normal','Difícil','Craque'].map((x,i)=>`<option value="${i}" ${i===this.app.settings.difficulty?'selected':''}>${x}</option>`).join('')}</select></div><div><label for="duration">DURAÇÃO DA PARTIDA</label><select id="duration">${[120,240,360,600].map(v=>`<option value="${v}" ${v===this.app.settings.duration?'selected':''}>${v/60} minutos</option>`).join('')}</select></div><div><label for="stadium">AMBIENTE</label><select id="stadium"><option value="day">Tarde de futebol</option><option value="night">Noite de decisão</option></select></div></div><div class="button-row">${button('next','ESCALAÇÃO & TÁTICA →',true)}</div>`);
   this.click('back',()=>this.home());document.getElementById('home-team').onchange=e=>{s.home=e.target.value;document.getElementById('home-card').innerHTML=this.clubCard(s.home);};const away=document.getElementById('away-team');if(away)away.onchange=e=>{s.away=e.target.value;document.getElementById('away-card').innerHTML=this.clubCard(s.away);};document.getElementById('stadium').value=this.app.settings.stadium;
   this.click('next',()=>{this.app.settings.difficulty=+document.getElementById('difficulty').value;this.app.settings.duration=+document.getElementById('duration').value;this.app.settings.stadium=document.getElementById('stadium').value;this.app.saveSettings();s.lineup=[...this.app.data.get(s.home).players];s.formation=this.app.data.get(s.home).formation;this.lineup(false);});}
  lineup(inMatch=false){if(!inMatch&&this.setup.mode==='penalties'){this.penaltySetup();return;}const a=this.app,s=this.setup,t=inMatch?a.match.teams[a.match.human]:null,players=inMatch?t.players:s.lineup,bench=inMatch?t.bench:players.slice(11),formation=inMatch?t.formation:s.formation,tactics=inMatch?t.tactics:s.tactics;this.selectedSlot=null;
   this.show(`${this.head(inMatch?'ÁREA TÉCNICA':'PREPARAÇÃO',inMatch?`Substituições · ${t.subs}/5`:'Seu time, seu jogo')}<div class="roster-layout"><div><label for="formation">FORMAÇÃO</label><select id="formation">${Object.keys(B.FORMATIONS).map(f=>`<option ${f===formation?'selected':''}>${f}</option>`).join('')}</select><div class="pitch-mini" id="mini-pitch">${this.pitch(players,formation)}</div><div class="settings-grid">${[['mentality','MENTALIDADE',['Defensiva','Equilibrada','Ofensiva']],['pressure','PRESSÃO',['Baixa','Média','Alta']],['line','LINHA',['Baixa','Média','Alta']],['attack','ATAQUE',['Posse','Equilibrado','Contra-ataque']]].map(([key,name,values])=>`<div><label for="tactic-${key}">${name}</label><select id="tactic-${key}">${values.map(v=>`<option ${v===tactics[key]?'selected':''}>${v}</option>`).join('')}</select></div>`).join('')}</div></div><div class="panel"><div class="sub">Selecione um titular e depois um reserva para trocar.</div><div class="roster" id="roster">${this.rosterRows(players.slice(0,11),bench,inMatch)}</div><div class="micro">GER = ATRIBUTO INTERNO DE GAMEPLAY<br>— = NÚMERO NÃO VERIFICADO · GK / DF / MF / FW</div></div></div><div class="button-row">${button('start',inMatch?'VOLTAR AO JOGO →':s.competition?'INICIAR PARTIDA →':['league','cup'].includes(s.mode)?'INICIAR COMPETIÇÃO →':'ENTRAR EM CAMPO →',true)}</div>`);
   this.click('back',()=>inMatch?this.pause(a.match.state==='half'):s.competition?this.competition():this.selection());document.getElementById('formation').onchange=e=>{if(inMatch){t.formation=e.target.value;const pos=B.FORMATIONS[t.formation];t.players.forEach((p,i)=>{p.role=pos[i].role;p.home={x:(t.dir>0?pos[i].x:1-pos[i].x)*B.FIELD.w,y:pos[i].y*B.FIELD.h};});}else s.formation=e.target.value;document.getElementById('mini-pitch').innerHTML=this.pitch(players,e.target.value);};for(const k of Object.keys(tactics))document.getElementById('tactic-'+k).onchange=e=>tactics[k]=e.target.value;
   this.el.querySelectorAll('[data-slot]').forEach(el=>el.onclick=()=>{const index=+el.dataset.slot;if(players[index].red){this.toast('Um jogador expulso não pode ser substituído.');return;}this.selectedSlot=index;this.el.querySelectorAll('.roster-row').forEach(r=>r.classList.remove('selected'));el.closest('.roster-row').classList.add('selected');});
   this.el.querySelectorAll('[data-bench]').forEach(el=>el.onclick=()=>{if(this.selectedSlot===null){this.toast('Selecione primeiro quem vai sair.');return;}const index=+el.dataset.bench,slot=this.selectedSlot;if(slot===0&&bench[index].position!=='GK'||slot!==0&&bench[index].position==='GK'){this.toast('Troque goleiro por goleiro e jogador de linha por jogador de linha.');return;}if(inMatch){if(['penalty','goal'].includes(a.match.state)){this.toast('Aguarde o fim do lance.');return;}const old=t.players[slot],fresh=t.substitute(slot,index);if(!fresh){this.toast('Limite de cinco substituições atingido.');return;}if(a.match.controlled===old)a.match.controlled=fresh;if(a.match.ball.owner===old)a.match.ball.owner=fresh;if(a.match.restart?.taker===old)a.match.restart.taker=fresh;a.match.pendingOffside=a.match.pendingOffside.filter(p=>p!==old);a.match.ball.pass=null;a.match.message(`ENTRA ${fresh.name.toUpperCase()}`,2);}else [s.lineup[slot],s.lineup[11+index]]=[s.lineup[11+index],s.lineup[slot]];this.lineup(inMatch);});
   this.click('start',()=>{if(inMatch){a.resume();return;}if(['league','cup'].includes(s.mode)&&!s.competition){a.competition.create(s.mode,s.home,a.data.teams);this.competition();}else a.start(s.home,s.away,{...s});});}
  pitch(players,formation){return B.FORMATIONS[formation].map((p,i)=>`<span class="pin" style="left:${p.x*100}%;top:${p.y*100}%">${players[i]?.shirtNumber??i+1}<span class="pin-label">${esc(players[i]?.name.split(' ').slice(-1)[0])}</span></span>`).join('');}
  rosterRows(players,bench,inMatch){const row=(p,i,reserve)=>`<div class="roster-row"><small>${p.shirtNumber??'—'}</small><span>${esc(p.name)} ${p.red?'🟥':p.yellow?'🟨':''}<small style="display:block">${p.position}${inMatch&&!reserve?' · '+Math.round(p.energy*100)+'%':''}</small></span><b>${p.overall}</b><button ${reserve?'data-bench':'data-slot'}="${i}">${reserve?'ENTRA':'SAI'}</button></div>`;return `<div class="roster-title">TITULARES · 11</div>${players.map((p,i)=>row(p,i,false)).join('')}<div class="roster-title">BANCO DE RESERVAS</div>${bench.map((p,i)=>row(p,i,true)).join('')}`;}
  stats(m){const [a,b]=m.teams.map(t=>t.stats),total=a.possession+b.possession;return [['Posse de bola',total?Math.round(a.possession/total*100)+'%':'50%',total?Math.round(b.possession/total*100)+'%':'50%'],['Chutes',a.shots,b.shots],['No gol',a.onTarget,b.onTarget],['Passes',a.passes,b.passes],['Passes certos',a.completed,b.completed],['Faltas',a.fouls,b.fouls],['Escanteios',a.corners,b.corners],['Impedimentos',a.offsides,b.offsides]].map(([name,x,y])=>`<div class="stats-line"><b>${x}</b><span>${name}</span><b>${y}</b></div>`).join('');}
  pause(half=false){const m=this.app.match;this.app.input.enabled=false;this.show(`<div class="pause-box">${this.head('RESPIRA. ORGANIZA. VOLTA.',half?m.banner:'Jogo pausado','Jogar')}<div class="score-big">${m.teams[0].data.shortName} ${m.teams[0].score} : ${m.teams[1].score} ${m.teams[1].data.shortName}</div><div>${this.stats(m)}</div><div class="button-row">${button('exit','SAIR DA PARTIDA')}${button('subs','ESCALAÇÃO & TÁTICA')}${button('resume',half?'VAMOS PARA O JOGO →':'CONTINUAR →',true)}</div></div>`);this.click('back',()=>this.app.resume());this.click('resume',()=>this.app.resume());this.click('subs',()=>this.lineup(true));this.click('exit',()=>{this.show(`${this.head('PARTIDA EM ANDAMENTO','Sair da partida?')}<p class="sub">O resultado atual será descartado. As rodadas já concluídas continuam salvas.</p><div class="button-row">${button('exit-confirm','SAIR PARA O MENU',true)}</div>`);this.click('back',()=>this.pause(half));this.click('exit-confirm',()=>this.home());});}
  result(){const m=this.app.match,win=m.penalties?.winner,headline=win!==undefined&&win!==null?`${m.teams[win].data.name} venceu nos pênaltis`:'Fim de jogo';this.show(`<div class="pause-box">${this.head('APITO FINAL',esc(headline),'Menu')}<div class="score-big">${m.teams[0].data.shortName} ${m.teams[0].score} : ${m.teams[1].score} ${m.teams[1].data.shortName}</div>${m.penalties?`<p class="sub" style="text-align:center">Pênaltis: ${m.penalties.scores.join(' × ')}</p>`:''}${this.stats(m)}<div class="button-row">${button('rematch','JOGAR NOVAMENTE')}${button('result-next',m.options.competition?'VER COMPETIÇÃO →':'NOVA PARTIDA →',true)}</div></div>`);this.click('back',()=>this.home());this.click('rematch',()=>{this.app.start(m.teams[0].data.id,m.teams[1].data.id,{...m.options,competition:false,mode:m.mode==='cup'?'quick':m.mode});});this.click('result-next',()=>{this.app.match=null;document.body.classList.remove('playing');if(m.options.competition)this.competition();else this.selection();});}
  competition(){const a=this.app,c=a.competition.current;document.body.classList.remove('playing');a.match=null;const name=id=>esc(a.data.get(id)?.name||id),fixture=a.competition.fixture(),league=c.type==='league';this.show(`${this.head('SUA TEMPORADA',league?'Campeonato Brasileiro':'Copa Brasil Arcade','Menu')}<div class="notice">${c.complete?`CAMPEÃO: ${name(c.champion).toUpperCase()}`:league?`RODADA ${c.round+1} DE 38 · ${name(c.team)}`:['QUARTAS DE FINAL','SEMIFINAL','FINAL'][c.round]} · SAVE LOCAL</div>${league?`<div class="table-scroll"><table><thead><tr><th>#</th><th>CLUBE</th>${['P','J','V','E','D','GP','GC','SG'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${a.competition.standings().map((t,i)=>`<tr class="${t.id===c.team?'mine':''}"><td>${i+1}</td><td>${name(t.id)}</td>${[t.p,t.j,t.v,t.e,t.d,t.gp,t.gc,t.gp-t.gc].map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:`<div class="bracket">${c.rounds.map((round,i)=>round.map(g=>`<div class="fixture"><label>${['QUARTAS','SEMIFINAL','FINAL'][i]}</label>${name(g.home)} <b>${g.result?g.result.join(' × '):'×'}</b> ${name(g.away)}${g.penalties?`<div class="micro">Pênaltis ${g.penalties.join(' × ')}</div>`:''}</div>`).join('')).join('')}</div>`}${fixture?`<div class="club-card"><div><label>PRÓXIMO CONFRONTO</label><h3>${name(fixture.home)} × ${name(fixture.away)}</h3></div></div>`:''}${c.history.length?`<details class="micro"><summary>RESULTADOS DA ÚLTIMA RODADA</summary>${c.history.at(-1).games.map(g=>`<p>${name(g.home)} ${g.result.join(' × ')} ${name(g.away)}</p>`).join('')}</details>`:''}<div class="button-row">${button('new-season','NOVA TEMPORADA')}${!c.complete?button('play-fixture',fixture?'PREPARAR PRÓXIMO JOGO →':'ACOMPANHAR PRÓXIMA FASE →',true):''}</div>`);
   this.click('back',()=>this.home());this.click('new-season',()=>{this.setup.mode=c.type;this.setup.competition=false;this.selection();});this.click('play-fixture',()=>{if(!fixture){a.competition.completeRound();this.competition();return;}const human=fixture.home===c.team?0:1;this.setup={...this.setup,home:fixture.home,away:fixture.away,mode:c.type==='league'?'league':'cup',competition:true,human,formation:a.data.get(c.team).formation,lineup:[...a.data.get(c.team).players]};this.lineupCompetition(human);});}
  lineupCompetition(){this.lineup(false);}
  options(){const a=this.app;this.show(`${this.head('DO SEU JEITO','Opções & controles')}<div class="stat-grid"><div class="panel"><label for="preset">ESQUEMA DE TECLADO</label><select id="preset"><option value="classic">Clássico · setas + Z/X/C/A/S/D</option><option value="wasd">WASD · J/K/L + Shift/Q/E</option></select><div class="control-list">${Object.entries({up:'Cima',down:'Baixo',left:'Esquerda',right:'Direita',pass:'Passe / carrinho',shoot:'Chute / bote',long:'Lançamento',sprint:'Corrida',switch:'Trocar jogador',context:'Drible / contextual',pause:'Pausar'}).map(([k,v])=>`<div>${v}<button data-bind="${k}">${esc(a.input.bindings[k].replace('Key','').replace('Arrow',''))}</button></div>`).join('')}</div><div class="micro">CLIQUE EM UMA TECLA PARA REDEFINIR. CONFLITOS SÃO TROCADOS.</div></div><div><h3>Controle nas mãos.</h3><p class="controls-help">Segure passe ou chute para carregar a força. Solte para executar. Direcione antes de soltar para escolher o receptor ou canto.<br><br>Duplo toque na direção: arrancada.<br>Contextual com bola: corte lateral; no alto: cabeçada ou voleio.<br>F2: informações de depuração.<br><br>PÊNALTIS: segure a direção e pressione Passe (fraco), Chute (médio) ou Lançamento (forte). Contextual + direção faz a finta. Na defesa, direção + Chute ou Lançamento: cima salta, baixo abaixa. Não é preciso carregar a força.<br>Gamepad nos pênaltis: botão esquerdo = fraco; inferior = médio; direito = forte; superior = finta. Defesa: inferior ou direito.</p><p class="sub">Celular: direcional virtual com diagonais e corrida por R; passe, chute e lançamento por A/B/C; L troca jogador, Y dribla e PAUSA abre o menu. Segure e solte passe/chute para carregar. Nos pênaltis, A/B/C escolhem a força, Y + direcional faz a finta, e B/C defendem. Vários botões podem ser usados ao mesmo tempo.<br><br>Gamepad: analógico / direcional para mover. A/× passa, X/□ chuta, B/○ lança, RB/R1 corre, LB/L1 troca, Y/△ contextual, Start pausa. Mapeamento padrão da Gamepad API.</p><p class="micro">${esc(a.input.gamepadName||'Conecte um controle e pressione um botão para detectar.')}</p><h3>Atualize seu elenco.</h3><p class="sub">Importe um JSON no formato de data/import/roster-template.json. Dados importados ficam neste navegador.</p><label class="file-label">IMPORTAR ELENCO JSON<input type="file" id="roster-file" accept=".json,application/json"></label><p class="notice">Elencos: nomes e posições consultados em fontes públicas. Número, nascimento, altura e pé desconhecidos ficam vazios. Atributos são estimativas internas, não avaliações oficiais.</p></div></div>`);
   this.click('back',()=>a.match?this.pause(a.match.state==='half'):this.home());document.getElementById('preset').onchange=e=>{a.input.bindings={...B.KEY_PRESETS[e.target.value]};B.safeStorage.set('controls',a.input.bindings);this.options();};this.el.querySelectorAll('[data-bind]').forEach(el=>el.onclick=()=>{el.textContent='TECLA...';a.input.rebind=key=>{a.input.bind(el.dataset.bind,key);this.options();};});document.getElementById('roster-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const data=JSON.parse(await file.text());const team=a.data.importRoster(data);this.toast(`Elenco de ${team} atualizado.`);}catch(error){this.toast(error.message);}};
  }
 };
})();
