'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
let pw;
try { pw=require('playwright'); }
catch { pw=require(path.join(process.env.USERPROFILE||'', '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')); }
(async()=>{
 const executable=process.env.BSS_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
 const browser=await pw.chromium.launch({headless:true,...fs.existsSync(executable)?{executablePath:executable}:{}});
 const page=await browser.newPage({viewport:{width:1366,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 try {
  await page.goto(process.env.BSS_URL||'http://127.0.0.1:8000');
  await page.waitForSelector('#mode-quick');
  await page.screenshot({path:'tests/menu.png'});
  await page.click('#mode-quick');
  assert.equal(await page.locator('#home-team option').count(),208);
  await page.click('#next');
  await page.selectOption('#formation','4-3-3');
  await page.click('#start');
  await page.waitForTimeout(1200);
  await page.keyboard.down('z');await page.waitForTimeout(180);await page.keyboard.up('z');
  await page.waitForTimeout(600);
  assert.equal(await page.evaluate(()=>BSS.app.match.state),'play');
  const before=await page.evaluate(()=>BSS.app.match.controlled.x);
  await page.keyboard.down('ArrowRight');await page.waitForTimeout(600);await page.keyboard.up('ArrowRight');
  const after=await page.evaluate(()=>BSS.app.match.controlled.x);
  assert.ok(after>before);
  await page.keyboard.down('x');await page.waitForTimeout(350);await page.keyboard.up('x');
  await page.waitForTimeout(200);
  await page.screenshot({path:'tests/match.png'});
  await page.keyboard.press('Escape');await page.waitForSelector('#resume');
  await page.click('#subs');
  const benchIndex=await page.evaluate(()=>BSS.app.match.teams[0].bench.findIndex(p=>p.position!=='GK'));
  await page.locator('[data-slot="1"]').click();
  await page.locator(`[data-bench="${benchIndex}"]`).click();
  assert.equal(await page.evaluate(()=>BSS.app.match.teams[0].subs),1);
  await page.click('#start');
  await page.evaluate(()=>{const m=BSS.app.match;m.state='play';m.clock=2700+m.added;});
  await page.waitForSelector('#resume');await page.click('#resume');
  assert.equal(await page.evaluate(()=>BSS.app.match.period),2);
  await page.evaluate(()=>{const m=BSS.app.match;m.state='play';m.clock=5400+m.added;});
  await page.waitForSelector('#result-next');await page.screenshot({path:'tests/result.png'});
  await page.click('#rematch');
  assert.equal(await page.evaluate(()=>BSS.app.match.teams[0].score),0);
  await page.keyboard.press('Escape');await page.waitForSelector('#exit');await page.click('#exit');await page.click('#exit-confirm');
  await page.click('#mode-league');await page.click('#next');
  assert.equal(await page.locator('tbody tr').count(),20);
  await page.click('#play-fixture');await page.click('#start');
  await page.evaluate(()=>{const m=BSS.app.match;m.state='play';m.period=2;m.clock=5400+m.added;});
  await page.waitForSelector('#result-next');await page.click('#result-next');
  assert.ok((await page.locator('.notice').first().textContent()).includes('Rodada 2'));
  await page.reload();await page.waitForSelector('#mode-league');await page.click('#mode-league');
  assert.ok((await page.locator('.notice').first().textContent()).includes('Rodada 2'));
  await page.screenshot({path:'tests/league.png'});
  await page.click('#back');await page.click('#mode-penalties');await page.click('#next');await page.click('#start');
  await page.keyboard.down('ArrowRight');await page.keyboard.down('x');await page.waitForTimeout(450);
  await page.keyboard.up('ArrowRight');await page.keyboard.up('x');await page.waitForTimeout(2200);
  assert.ok(await page.evaluate(()=>BSS.app.match.penalties.kicks[0].length>=1));
  await page.screenshot({path:'tests/penalties.png'});
  await require('./browser-penalties.cjs')(page,assert);
  await require('./browser-layout.cjs')(page,assert);
  await require('./browser-ball.cjs')(page,assert);
  await require('./browser-gameplay.cjs')(page,assert);
  await require('./browser-free-kicks.cjs')(page,assert);
  await require('./browser-scenarios.cjs')(page,assert);
  await page.goto('file:///'+path.resolve('index.html').replaceAll('\\','/'));
  await page.waitForSelector('#mode-quick');
  assert.equal(await page.evaluate(()=>BSS.app.data.teams.length),208);
  await page.click('#mode-options');await page.selectOption('#preset','wasd');
  assert.equal(await page.evaluate(()=>BSS.app.input.bindings.left),'KeyA');
  await page.click('[data-bind="shoot"]');await page.keyboard.press('u');
  assert.equal(await page.evaluate(()=>BSS.app.input.bindings.shoot),'KeyU');
  await page.reload();await page.waitForSelector('#mode-quick');
  assert.equal(await page.evaluate(()=>BSS.app.input.bindings.shoot),'KeyU');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'tests/mobile-menu.png'});
  assert.deepEqual(errors,[]);
  console.log('Browser PASS: HTTP, file://, menus, teclado, passe, chute, substituição, reinício, intervalo, fim, liga/save, pênaltis, controles personalizados. Sem erros no console.');
 } catch(e) {
  await page.screenshot({path:'tests/failure.png'});
  console.error('Console errors:',errors);
  console.error('State:',await page.evaluate(()=>({state:window.BSS?.app?.match?.state,paused:window.BSS?.app?.paused,screen:document.getElementById('screen')?.innerText.slice(0,300)})));
  throw e;
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
