const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=global;global.localStorage={getItem:()=>null,setItem(){}};
const root=path.resolve(__dirname,'..');for(const file of ['data/bundle.js',...['engine','formations','physics','data-loader','player','ball','team','ai','penalty','free-kick','match','renderer','cinematics'].map(s=>'js/'+s+'.js')])vm.runInThisContext(fs.readFileSync(path.join(root,file),'utf8'));
const data=new BSS.DataManager();data.raw=BSS_DATA;data.hydrate();const make=()=>{const m=new BSS.Match(data.teams[0],data.teams[1],{seed:7});m.cinema=new BSS.Cinematics(m);m.cinema.queue=[];return m;};const drain=m=>{let n=0;while(m.cinema.active&&n++<30)m.cinema.next();assert.ok(n<30);};
test('sorteio aplica escolha e alterna saída no segundo tempo',()=>{const m=make();m.cinema.add('toss',18,{stage:2,choice:0,winner:1});m.update(3);assert.equal(m.restart.team,1);m.resumeHalf();assert.equal(m.restart.team,0);});
test('replay não modifica relógio, bola, energia ou placar',()=>{const m=make();m.state='play';m.cinema.capture();m.ball.x+=30;m.cinema.capture();m.cinema.replay('teste');const before=JSON.stringify([m.clock,m.ball.x,m.teams.map(t=>t.score),m.players.map(p=>p.energy)]);m.update(.05);assert.equal(JSON.stringify([m.clock,m.ball.x,m.teams.map(t=>t.score),m.players.map(p=>p.energy)]),before);assert.notEqual(m.cinema.active.data.frames[0].ball.x,m.ball.x);});
test('gol de virada e hat trick acumulam cenas e gol contra não conta',()=>{const m=make(),c=m.cinema;m.lastScorer=m.teams[0].players[9];m.teams[1].score=1;c.record(.1);for(let i=1;i<=3;i++){m.teams[0].score=i;c.goal({team:0});}assert.equal(c.queue.filter(s=>s.type==='comeback').length,1);assert.equal(c.queue.filter(s=>s.type==='hat').length,1);c.goal({team:1,ownGoal:true});assert.equal(c.goals.get('0:'+m.lastScorer.id),3);});
test('gol real retoma saída sem pontuação duplicada',()=>{const m=make(),F=BSS.FIELD;m.state='play';Object.assign(m.ball,{x:F.w+2,px:F.w-3,y:F.cy,py:F.cy,z:0,pz:0});m.ball.lastTouch=m.teams[0].players[9];m.boundaries();assert.equal(m.cinema.active.type,'goal');drain(m);assert.equal(m.state,'restart');assert.equal(m.restart.team,1);assert.equal(m.teams[0].score,1);});
test('pênalti tem árbitro e replay, gol retorna à saída',()=>{const m=make();m.cinema.capture();m.cinema.capture();m.setupPenalty(0,false);assert.deepEqual(m.cinema.queue.map(s=>s.type),['referee','replay']);drain(m);m.penaltyResult(true,'GOL');m.resolvePenalty();assert.ok(m.cinema.queue.some(s=>s.type==='goal'));drain(m);assert.equal(m.restart.team,1);assert.equal(m.teams[0].score,1);});
test('resultado só é emitido uma vez depois da cena final',()=>{const m=make();let n=0;m.onEvent=t=>{if(t==='finished')n++;};m.teams[1].score=2;m.finish();m.finish();assert.equal(m.finished,false);assert.equal(m.cinema.active.data.side,1);drain(m);m.finish();assert.equal(n,1);assert.equal(m.finished,true);});
test('substituição e falta preservam reinício e referências',()=>{const m=make();m.setRestart('FALTA',0,400,340);assert.equal(m.cinema.active.type,'referee');drain(m);const old=m.teams[0].players[1],fresh=m.teams[0].substitute(1,1);m.cinema.substitution(old,fresh);const state=m.state;drain(m);assert.equal(m.state,state);assert.equal(m.teams[0].players[1],fresh);});

