'use strict';
// Curated factual names and position groups from the public sources in data/sources.md.
// This script is only the initial seed. Edit data/*.json thereafter; build-data preserves edits.
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const rows=[
 ['flamengo','Flamengo','FLA','Rio de Janeiro','Maracanã','#ce343b','#172128','STRIPES_HORIZONTAL','flamengo/5981'],
 ['palmeiras','Palmeiras','PAL','São Paulo','Parque Antarctica','#19714d','#f2edd9','DETAILS','palmeiras/1963'],
 ['corinthians','Corinthians','COR','São Paulo','Neo Química Arena','#eeeede','#172128','DETAILS','corinthians/1957'],
 ['sao-paulo','São Paulo','SAO','São Paulo','Morumbi','#eeeede','#c8323c','STRIPES_HORIZONTAL','sao-paulo/1981'],
 ['santos','Santos','SAN','Santos','Vila Belmiro','#f3f0da','#252c31','SOLID','santos/1968'],
 ['fluminense','Fluminense','FLU','Rio de Janeiro','Maracanã','#8a3044','#35785e','STRIPES_VERTICAL','fluminense/1961'],
 ['botafogo','Botafogo','BOT','Rio de Janeiro','Nilton Santos','#252c31','#eeeede','STRIPES_VERTICAL','botafogo/1958'],
 ['vasco','Vasco da Gama','VAS','Rio de Janeiro','São Januário','#252c31','#eeeede','SASH','vasco-da-gama/1974'],
 ['gremio','Grêmio','GRE','Porto Alegre','Arena do Grêmio','#54aaca','#202c35','STRIPES_VERTICAL','gremio/5926'],
 ['internacional','Internacional','INT','Porto Alegre','Beira-Rio','#d63c42','#f1eadc','DETAILS','internacional/1966'],
 ['cruzeiro','Cruzeiro','CRU','Belo Horizonte','Mineirão','#366ac4','#f0eade','SOLID','cruzeiro/1954'],
 ['atletico-mg','Atlético-MG','CAM','Belo Horizonte','Arena MRV','#242d33','#eeeede','STRIPES_VERTICAL','atletico-mineiro/1977'],
 ['bahia','Bahia','BAH','Salvador','Fonte Nova','#eeeede','#3d76bf','DETAILS','bahia/1955'],
 ['vitoria','Vitória','VIT','Salvador','Barradão','#be313b','#20272d','STRIPES_HORIZONTAL','vitoria/1962'],
 ['athletico','Athletico-PR','CAP','Curitiba','Arena da Baixada','#c4373f','#222b30','STRIPES_VERTICAL','athletico/1967'],
 ['coritiba','Coritiba','CFC','Curitiba','Couto Pereira','#eeeecc','#307153','STRIPES_HORIZONTAL','coritiba/1982'],
 ['bragantino','Red Bull Bragantino','RBB','Bragança Paulista','Nabi Abi Chedid','#eeeede','#c33744','DETAILS','red-bull-bragantino/1999'],
 ['mirassol','Mirassol','MIR','Mirassol','José Maria de Campos Maia','#e3c54c','#287d58','DETAILS','mirassol/21982'],
 ['chapecoense','Chapecoense','CHA','Chapecó','Arena Condá','#348d57','#edead8','DETAILS','chapecoense/21845'],
 ['remo','Remo','REM','Belém','Mangueirão','#253759','#eeeede','SOLID','remo/2012']
];
const squads={
 flamengo:{GK:'Agustín Rossi|Andrew|Dyogo Alves',DF:'Danilo|Léo Pereira|Alex Sandro|Léo Ortiz|Emerson Royal|Guillermo Varela|Ayrton Lucas|Vitão',MF:'Giorgian de Arrascaeta|Lucas Paquetá|Jorginho|Samuel Lino|Gonzalo Plata|Jorge Carrascal|Nicolás de la Cruz|Luiz Araújo|Erick Pulgar|Saúl Ñíguez|Evertton Araujo',FW:'Pedro Guilherme|Bruno Henrique|Joaquín Freitas|Anthony Valencia'},
 palmeiras:{GK:'Carlos Miguel:1|Marcelo Lomba:14|Bruno Bertinato:21',DF:'Agustín Giay:4|Gustavo Gómez:15|Murilo:26|Joaquín Piquerez:22|Alexander Barboza:2|Benedetti:43|Bruno Fuchs:3|Khellven:12|Arthur:56|Jefté:6',MF:'Andreas Pereira:8|Emiliano Martínez:32|Felipe Anderson:7|Marlon Freitas:17|Lucas Evangelista:30|Mauricio:18|Larson:48',FW:'Vitor Roque:9|López:42|Paulinho:10|Ramón Sosa:19|Jhon Arias:11'},
 corinthians:{GK:'Hugo Souza|Felipe Longo|Kauê Camargo',DF:'Matheuzinho|Matheus Bidu|Gustavo Henrique|Gabriel Paulista|André Ramalho|Fabrizio Angileri|João Pedro Tchoca|Hugo|Pedro Milans',MF:'Rodrigo Garro|Breno Bidon|André Carrillo|Kaio César|Raniele|Allan|André Luiz|Zakaria Labyad|Matheus Pereira|Charles|Dieguinho|Alex Santana',FW:'Memphis Depay|Yuri Alberto|Jesse Lingard|Gui Negão|Pedro Raul|Vitinho|Kayke Ferrari'},
 'sao-paulo':{GK:'Rafael:23|Young:50|Carlos Coronel:31',DF:'Robert Arboleda:5|Wendell:18|Enzo Díaz:13|Rafael Tolói:2|Sabino:35|Domingos Duarte:22|Iago Borduchi:12|Lucas Ramon:19|Pedro Lima:32',MF:'Ferreirinha:11|Damián Bobadilla:16|Marcos Antônio:8|Pablo Maia:29|Artur:37|Cauly:80|Danielzinho|Victor Sá:27',FW:'Lucas Moura:7|Jonathan Calleri:9|Luciano:10|Ryan Francisco:49|André Silva:17|Gustavo Santana:43'},
 santos:{GK:'Gabriel Brazão|João Paulo|Diogenes',DF:'Rodinei|Igor Vinícius|Lucas Veríssimo|Gonzalo Escobar|Luan Peres|Alexis Duarte|Vinicius Rodrigues Lira',MF:'Benjamín Rollheiser|Arthur|Gabriel Bontempo|João Schmidt|Everton|Miguelito|Álvaro Barreal|Gabriel Menino|Willian Arão|Thaciano|Lima|Christian Oliva',FW:'Neymar|Gabriel Barbosa|Rony|Moisés'},
 fluminense:{GK:'Fábio|Marcelo Pitaluga|Vitor Eudes',DF:'Thiago Silva|Guilherme Arana|Ignácio|Samuel Xavier|Renê|Juan Pablo Freytes|Guga|Julián Millán|Igor Rabello',MF:'Yeferson Soteldo|Jefferson Savarino|Matheus Martinelli|Luciano Acosta|Agustín Canobbio|Kevin Serna|Ganso|Hércules|Alisson|Nonato|Otávio',FW:'Hulk|Germán Cano|John Kennedy|Rodrigo Castillo|Riquelme Felipe'},
 botafogo:{GK:'Cristhian Loor|Warleson|Gabriel Batista',DF:'Alex Telles|Vitinho|Nahuel Ferraresi|Mateo Ponte|Marçal|Kaio Pantaleão|Arthur Chaves|Jhoan Hernandez',MF:'Hakim Ziyech|Danilo Santos|Allan|Álvaro Montoro|Cristian Medina|Jordan Barrera|Edenilson|Lucas Villalba|Huguinho|Domingos Andrade',FW:'Arthur Cabral|Tiquinho Soares|Kadir Barría|Júnior Santos|Matheus Martins|Danilo Pereira'},
 vasco:{GK:'Léo Jardim|Daniel Fuzato|Pablo',DF:'Paulo Henrique|Carlos Cuesta|Cuiabano|Robert Renan|Lucas Piton|Puma Rodríguez|Alan Saldivia|Lucas Freitas|Gabriel Pereira',MF:'Andrés Gómez|Marino Hinestroza|Nuno Moreira|Thiago Mendes|Cauan Barros|Johan Rojas|Santiago Sosa|Tchê Tchê|Alan Lescano|Jair',FW:'Facundo Colidio|Brenner|Claudio Spinelli|Bruno Duarte|Adson|David'},
 gremio:{GK:'Weverton|Gabriel Grando|Thiago Beltrame',DF:'Walter Kannemann|Marcos Rocha|Marlon|Fabián Balbuena|Caio Paulista|Wagner Leonardo|Gustavo Martins|João Pedro',MF:'Erick Noriega|Cristian Pavón|Mathias Villasanti|Filip Krovinović|Francis Amuzu|Tiaguinho|Juan Nardoni|Dodi|Danilo Barbosa',FW:'Carlos Vinícius|Martin Braithwaite|Tetê|José Enamorado|Jovane Cabral|Matheus Nascimento'},
 internacional:{GK:'Matheus Cunha|Sergio Rochet|Anthoni',DF:'Félix Torres|Alexandro Bernabei|Guillermo Maripán|Gabriel Mercado|Bruno Gomes|Victor Gabriel|Matheus Bahia|Braian Aguirre',MF:'Alan Patrick|Paulinho Paula|Thiago Maia|Vitinho|Niclas Eliasson|Bruno Henrique|Rodrigo Villagra|Calebe Gonçalves|Ronaldo',FW:'Antonio Sanabria|Johan Carbonero|Kayky|Alerrandro'},
 cruzeiro:{GK:'Cássio|Otávio Costa|Léo Aragão',DF:'Matías Viña|Fabrício Bruno|Fagner|William Furtado|Lucas Villalba|Jonathan Jesus|João Marcelo|Gabriel Rojas',MF:'Gerson|Matheus Pereira|Wesley|Keny Arroyo|Gabriel Pec|Zé Lucas|Lucas Romero|Matheus Henrique|Lucas Silva|Wanderson',FW:'Kaio Jorge|Luis Sinisterra|Néiser Villarreal|Luciano Rodríguez|Bruno Rodrigues|Kaique Kenji'},
 'atletico-mg':{GK:'Everson|Gabriel Delfim|Robert Alves',DF:'Renan Lodi|Lyanco|Ruan|Natanael|Vitor Hugo|Vitão|Léo Duarte',MF:'Reinier|Fred|Gustavo Scarpa|Victor Hugo|Kevin Castaño|Alan Franco|Maycon|Ángelo Preciado|Bernard|Tomás Cuello|Alexsander|Igor Gomes',FW:'Dudu|Alan Minda|Mateo Cassierra|Thiago Borbas'},
 bahia:{GK:'Ronaldo|Léo Vieira|Guido Herrera',DF:'David Duarte|Kanu|Luiz Gustavo|Román Gómez|Marcos Victor|José Guilherme|Fredi Gomes|Marco Moreno',MF:'Everton Ribeiro|Luciano Juba|Jean Lucas|Rodrigo Nestor|Cristian Olivera|Caio Alexandre|Ruan Pablo|Michel Araújo|Nicolás Acevedo|Mateo Sanabria|Erick',FW:'Erick Pulga|Alejo Véliz|Willian José|Dell|Everaldo|Ademir'},
 vitoria:{GK:'Lucas Arcanjo|Alexandre Fintelman|Yuri Sena',DF:'Cacá|Ramon|Luan Cândido|Emanuel Brítez|Camutanga|Jamerson|Nathan Mendes|Fabiano Souza|Zé Marcos',MF:'Erick|Matheuzinho|Walace|Tomás Pochettino|Gabriel Baralhas|Emmanuel Martínez|Osvaldo|Ignacio Laquintana|Dudu|Diego Tarzia',FW:'Marinho|Renato Kayzer|Renê Sousa|Fabrício Santos|Alex Bruno'},
 athletico:{GK:'Santos|Mycael|Matheus Soares',DF:'Lucas Esquivel|Arthur Dias|Gilberto Junior|Gilberto|Léo|Carlos Terán|Juan Felipe Aguirre|Dantas|Gastón Benavídez',MF:'Luiz Gustavo|Juan Portilla|Bruno Zapelli|Steven Mendoza|João Cruz|Dudu|Kerwin Vargas|Jádson|Isaac|Felipinho',FW:'Kevin Viveros|Leozinho|Jorge Rivaldo|Renan Viana'},
 coritiba:{GK:'Pedro Morisco|Keiller|Pedro Rangel',DF:'João Pedro Chermont|Fabricio Bustos|Maicon|Jacy Maranhão|Felipe Jonatan|Tinga|Tiago Cóser|Rodrigo Moledo|Bruno Melo',MF:'Josué|Breno Lopes|Lucas Ronier|Joaquín Lavega|Brian Ocampo|Thiago Santos|Nicolas Fonseca|Sebastián Gómez|Richard|Gustavo',FW:'Rodrigo Rodrigues|Keno|Pedro Rocha|Renato Marques|Fabinho|Brandão'},
 bragantino:{GK:'Tiago Volpi|Cleiton|Gustavo Reis',DF:'Vanderlan|Juninho Capixaba|Guzmán Rodríguez|José Andrés Hurtado|Gustavo Marques|Alix Vinicius|Agustin Sant Anna|Eduardo Santos',MF:'Rodriguinho|Fabinho|Lucas Barbosa|Henry Mosquera|Patrick|Matheus Fernandes|Gabriel Girotto|José Herrera|Ignacio Sosa|Bruno Praxedes|Eric Ramires',FW:'Wallace Yan|Isidro Pitta|Eduardo Sasha|Fernando|Vinicinho|Bruno Goncalves'}
};
const extraFile=path.join(root,'data/import/initial-extra.json');if(fs.existsSync(extraFile))Object.assign(squads,JSON.parse(fs.readFileSync(extraFile,'utf8')));
const teams=[],players=[];for(const [id,name,shortName,city,stadium,primaryColor,secondaryColor,pattern,sourcePath] of rows){if(!squads[id])continue;const kit=(base,secondary,shorts,pat)=>({shirtBaseColor:base,shirtSecondaryColor:secondary,shortsColor:shorts,socksColor:base,pattern:pat});const source=id==='palmeiras'?'https://www.palmeiras.com.br/elenco/':'https://www.sofascore.com/football/team/'+sourcePath;const t={id,name,shortName,city,stadium,primaryColor,secondaryColor,formation:'4-4-2',season:2026,source,checkedAt:'2026-09-30',kit:{home:kit(primaryColor,secondaryColor,['flamengo','gremio','santos','internacional','cruzeiro'].includes(id)?'#eeeecc':'#243039',pattern),away:kit(primaryColor==='#eeeede'||primaryColor==='#f3f0da'||primaryColor==='#eeeecc'?secondaryColor:'#eeeede',primaryColor,primaryColor,'DETAILS'),goalkeeper:kit('#e2a949','#263b38','#293d39','DETAILS')},players:[]};
 for(const [position,names] of Object.entries(squads[id]))for(const raw of names.split('|')){const [name,num]=raw.split(':'),p={id:id+'-'+(t.players.length+1),teamId:id,name,shirtNumber:num?+num:null,position,birthDate:null,height:null,preferredFoot:null,source,checkedAt:'2026-09-30'};if(id==='flamengo'&&name==='Agustín Rossi'){p.shirtNumber=1;p.height=193;p.preferredFoot='right';p.profileSource='https://www.flamengo.com.br/futebol/atleta/rossi';}players.push(p);t.players.push(p.id);}teams.push(t);}
fs.writeFileSync(path.join(root,'data/teams.json'),JSON.stringify(teams,null,2));fs.writeFileSync(path.join(root,'data/players.json'),JSON.stringify(players,null,2));fs.writeFileSync(path.join(root,'data/competitions.json'),JSON.stringify({season:2026,league:{name:'Brasileirão Arcade',teams:teams.map(t=>t.id),rounds:38,win:3,draw:1,loss:0},cup:{name:'Copa Brasil Arcade',size:8,extraTime:true,penalties:true}},null,2));require('./build-data');
